### ISSUE TITLE
Add install and run script like in paintera

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera-conversion-helper#4]
This will make the need for a fat jar obsolete for local runs
https://github.com/saalfeldlab/paintera/blob/8a4b0722534f76be4e4e6fb33aeb27b0fed5e9d1/install.sh
https://github.com/saalfeldlab/paintera/blob/label-multiset-type-argmax/paintera

**Comment by igorpisarev** [comment]
(just FYI) The artifact version can be easily obtained by parsing the auto-generated file `target/maven-archiver/pom.properties`, so that you don't have to bump it in the script every time a new version is released. For example, I have a primitive parser for it in n5-spark: https://github.com/saalfeldlab/n5-spark/blob/master/startup-scripts/jar_path_util.py
